// Supports ES6
// import { create, Whatsapp } from 'venom-bot';
const venom = require('venom-bot');
const { ListenerLayer } = require('venom-bot/dist/api/layers/listener.layer');
const GTU = require('./SelectionData');



venom
    .create({
        session: 'Test-Session', //name of session
        multidevice: false // for version not multidevice use false.(default: true)
    })
    .then((client) => start(client))
    .catch((erro) => {
        console.log(erro);
    });

function start(client) {
    client.onMessage(async (message) => {
        if (message.body.toUpperCase() === 'HELLO' && message.isGroupMsg === false) {
            console.log(message);
            client
                .sendText(message.from, `Hello ${message.notifyName}! this is an automated message generated by Dhyanesh `)
                .then((result) => {
                    console.log('Result: ', result); //return object success
                })
                .catch((erro) => {
                    console.error('Error when sending: ', erro); //return object error
                });
        }
        //******** */ course selection
        else if (message.body === 'Course' && message.isGroupMsg === false) {
            console.log(message);
            const courseList = [
                {
                    title: "Query:",
                    rows: [
                        { title: "Bachelor in Engineering(BE)", description: "" },
                        { title: "Diploma in Engineering(DI)", description: "" },
                        { title: "Bachelor in Pharmacy(BP)", description: "" }
                    ]
                }
            ];
            client.sendListMenu(message.from, '', '', 'Select the Course:', 'Select', courseList)
                .then((result) => {
                    // console.log('Result: ', result); //return object success
                    console.log("A List is requested from " + message.from);
                })
        }
        //******************************subject selection in BE
        else if (message.body === 'Bachelor in Engineering(BE)' && message.isGroupMsg === false) {
            console.log(message);
            const courseList = [
                {
                    title: "Query:",
                    rows: [
                        { title: "Computer Enginnering", description: "" },
                        { title: "Information and Technology", description: "" },
                        { title: "Electronics and Communictaion", description: "" },
                        { title: "Electrical Engineering", description: "" },
                        { title: "Civil Engineering", description: "" },
                        { title: "Mechanical Engineernig", description: "" },
                        { title: "Chemical Enginnering", description: "" },
                        { title: "Power Electronics", description: "" }
                    ]
                }
            ];
            await client.sendListMenu(message.from, '', '', 'Select the branch:', 'Select', courseList)
                .then((result) => {
                    // console.log('Result: ', result); //return object success
                    console.log("A List is requested from " + message.from);
                })
        }
        //***************************************Computer Engineering
        else if (message.body === 'Computer Enginnering' && message.isGroupMsg === false) {
            console.log(message);
            const semList = [
                {
                    title: "Query:",
                    rows: [
                        { title: "1/2", description: "" },
                        { title: "3", description: "" },
                        { title: "4", description: "" },
                        { title: "5", description: "" },
                        { title: "6", description: "" },
                        { title: "7", description: "" },
                        { title: "8", description: "" }
                    ]
                }
            ];
            await client.sendListMenu(message.from, '', '', 'Select the semister:', 'Select', semList)
                .then((result) => {
                    // console.log('Result: ', result); //return object success
                    console.log("A List is requested from " + message.from);
                })
        }
        //***************************************sem-3
        else if (message.body === '3' && message.isGroupMsg === false) {
            console.log(message);
            const subjectList = [
                {
                    title: "Query:",
                    rows: [
                        { title: "Effective Technical Communication", description: "" },
                        { title: "Probability and Statistics", description: "" },
                        { title: "Indian Constitution", description: "" },
                        { title: "Design Engineering - I A", description: "" },
                        { title: "Data Structures", description: "" },
                        { title: "Database Management Systems", description: "" },
                        { title: "Digital Fundamentals", description: "" }
                    ]
                }
            ];
            await client.sendListMenu(message.from, '', '', 'Select the subject:', 'Select', subjectList)
                .then((result) => {
                    // console.log('Result: ', result); //return object success
                    console.log("A List is requested from " + message.from);
                })
        }
        //***************************************Effective Technical Communication
        else if (message.body === 'Effective Technical Communication' && message.isGroupMsg === false) {
            console.log(message);

            await client
                .sendLinkPreview(
                    message.from,
                    'https://s3-ap-southeast-1.amazonaws.com/gtusitecirculars/Syallbus/3130004.pdf',
                    'Effective Technical Communication.pdf'
                )
                .then((result) => {
                    console.log('Result: ', result); //return object success
                })
                .catch((erro) => {
                    console.error('Error when sending: ', erro); //return object error
                });
        }



        // welcome message
        else if (message.isGroupMsg === false) {
            await client
                .sendText(message.from, `Hello ${message.notifyName}!\nWelcome to GTU Portal.`)
                .then((result) => {
                    console.log(' Welcome message from ', message.from); //return object success
                })
                .catch((erro) => {
                    console.error('Error when sending: ', erro); //return object error
                });

            const welcomeList = [
                {
                    title: "Query:",
                    rows: [
                        { title: "Course", description: "" },
                        { title: "Admission", description: "" },
                        { title: "Examination", description: "" }
                    ]
                }
            ];
            client.sendListMenu(message.from, '', '', ' Please select your query:', 'Select', welcomeList)
                .then((result) => {
                    // console.log('Result: ', result); //return object success
                    console.log("A List is requested from " + message.from);
                })
        }

    });


}
